### ISSUE TITLE
CodeBlue TODO 

### ISSUE THREAD

**Issue by crazy-oung** [crazy-oung/codeBlue#4]
- [x]  CodeBlue 소개 인덱스 페이지 작성 필요 

- [x] 사용자 웹페이지 상단부 출력 코드 사용자 별로 다르게 나타나도록 제이쿼리 코드로 교체

- [x] **질문 상세페이지에서 답글 출력**필요 

- [x] 프로필 페이지 구현
- [x] 프로필 페이지 CSS

- [ ] 사용자 아이디 중복 검사 기능 구현
- [ ] 이미지 업로드 기능 구현
----

**Comment by Lee-JinHyeok** [comment]
- [x] FAQ 상세페이지, 수정페이지, 삭제 기능 추가해야합니다

투두 사용후기 : 신기합니다..!

**Comment by apllec2960** [comment]
- [ ] 회원) 제휴병원 신청 폼 

- [ ] 관리자) 신청 정보를 받을 폼
